name: Pages Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy-to-kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Chart-testing (lint)
        id: lint
        uses: HexF/chart-testing-action@v3.0.0
        with:
          command: lint
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          install_local_path_provisioner: true
      - name: Install Kubectl
        run: |
          ls
          bash ./scripts/install-kubectl.sh

      - name: Helm Testing
        run: |
          bash ./scripts/helm-test.sh ${{ secrets.STAGING_NAMESPACE }} ${{ secrets.RELEASE_NAME }}

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs:  deploy-to-kind
    steps:
      - uses: actions/checkout@v2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Configure EKS
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name dees-cloud

      - name: Install Kubectl
        uses: actions/checkout@v2
      - name: Check kubectl
        run: |
          ls
          bash ./scripts/install-kubectl.sh
      - name: Install Helm3
        run: |
          bash ./scripts/install-helm.sh
      - name: Deploy to staging
        run: |
          bash ./scripts/deploy.sh ${{ secrets.STAGING_NAMESPACE }} ${{ secrets.RELEASE_NAME }}